package sk.seges.acris.etc;

import java.util.HashMap;
import java.util.Map;

public enum Countries {
    AFGHANISTAN("AFGHANISTAN", false, 5),
    ALBANIA("ALBANIA", false, 6),
    ALGERIA("ALGERIA", false, 7),
    AMERICAN_SAMOA("AMERICAN SAMOA", false, 8),
    ANDORRA("ANDORRA", false, 9),
    ANGOLA("ANGOLA", false, 10),
    ANGUILLA("ANGUILLA", false, 11),
    ANTIGUA_AND_BARBUDA("ANTIGUA AND BARBUDA", false, 12),
    ARGENTINA("ARGENTINA", false, 13),
    ARMENIA("ARMENIA", false, 14),
    ARUBA("ARUBA", false, 15),
    AUSTRALIA("AUSTRALIA", false, 16),
    AUSTRIA("AUSTRIA", true, 17),
    AZERBAIJAN("AZERBAIJAN", false, 18),
    BAHAMAS("BAHAMAS", false, 20),
    BAHRAIN("BAHRAIN", false, 21),
    BANGLADESH("BANGLADESH", false, 22),
    BARBADOS("BARBADOS", false, 23),
    BELARUS("BELARUS", false, 26),
    BELGIUM("BELGIUM", true, 24),
    BELIZE("BELIZE", false, 25),
    BENIN("BENIN", false, 27),
    BERMUDA("BERMUDA", false, 28),
    BHUTAN("BHUTAN", false, 29),
    BOLIVIA("BOLIVIA", false, 30),
    BOSNIA_AND_HERZEGOWINA("BOSNIA AND HERZEGOWINA", false, 32),
    BOTSWANA("BOTSWANA", false, 33),
    BRAZIL("BRAZIL", false, 34),
    BRUNEI_DARUSSALAM("BRUNEI DARUSSALAM", false, 36),
    BULGARIA("BULGARIA", true, 37),
    BURKINA_FASO("BURKINA FASO", false, 38),
    BURUNDI("BURUNDI", false, 39),
    CAMBODIA("CAMBODIA", false, 40),
    CAMEROON("CAMEROON", false, 41),
    CANADA("CANADA", false, 42),
    CAPE_VERDE("CAPE VERDE", false, 44),
    CAYMAN_ISLANDS("CAYMAN ISLANDS", false, 45),
    CENTRAL_AFRICAN_REPUBLIC("CENTRAL AFRICAN REPUBLIC", false, 46),
    CHAD("CHAD", false, 96),
    CHILE("CHILE", false, 97),
    CHINA("CHINA", false, 98),
    COLOMBIA("COLOMBIA", false, 47),
    COMOROS("COMOROS", false, 48),
    CONGO("CONGO, Democratic Republic of (was Zaire)", false, 49),
    COOK_ISLANDS("COOK ISLANDS", false, 50),
    COSTA_RICA("COSTA RICA", false, 51),
    CROATIA("CROATIA", false, 52),
    CUBA("CUBA", false, 53),
    CYPRUS("CYPRUS", true, 56),
    CZECH_REPUBLIC("CZECH REPUBLIC", true, 57),
    DENMARK("DENMARK", true, 58),
    DJIBOUTI("DJIBOUTI", false, 59),
    DOMINICA("DOMINICA", false, 60),
    DOMINICAN_REPUBLIC("DOMINICAN REPUBLIC", false, 61),
    ECUADOR("ECUADOR", false, 62),
    EGYPT("EGYPT", false, 63),
    EL_SALVADOR("EL SALVADOR", false, 64),
    ERITREA("ERITREA", false, 65),
    ESTONIA("ESTONIA", true, 66),
    ETHIOPIA("ETHIOPIA", false, 67),
    FALKLAND_ISLANDS("FALKLAND ISLANDS (MALVINAS)", false, 68),
    FAROE_ISLANDS("FAROE ISLANDS", false, 69),
    FIJI("FIJI", false, 70),
    FINLAND("FINLAND", true, 71),
    FRANCE("FRANCE", true, 72),
    FRENCH_GUIANA("FRENCH GUIANA", false, 73),
    FRENCH_POLYNESIA("FRENCH POLYNESIA", false, 74),
    GABON("GABON", false, 75),
    GAMBIA("GAMBIA", false, 225),
    GEORGIA("GEORGIA", false, 77),
    GERMANY("GERMANY", true, 78),
    GHANA("GHANA", false, 79),
    GIBRALTAR("GIBRALTAR", false, 80),
    GREECE("GREECE", true, 81),
    GREENLAND("GREENLAND", false, 82),
    GRENADA("GRENADA", false, 83),
    GUADELOUPE("GUADELOUPE", false, 84),
    GUAM("GUAM", false, 85),
    GUATEMALA("GUATEMALA", false, 86),
    GUINEA("GUINEA", false, 88),
    GUINEA_BISSAU("GUINEA-BISSAU", false, 89),
    GUYANA("GUYANA", false, 91),
    HAITI("HAITI", false, 92),
    HONDURAS("HONDURAS", false, 93),
    HONG_KONG("HONG KONG", false, 94),
    HUNGARY("HUNGARY", true, 95),
    ICELAND("ICELAND", false, 99),
    INDIA("INDIA", false, 100),
    INDONESIA("INDONESIA", false, 101),
    IRAN("IRAN (ISLAMIC REPUBLIC OF)", false, 102),
    IRAQ("IRAQ", false, 103),
    IRELAND("IRELAND", true, 104),
    ISRAEL("ISRAEL", false, 105),
    ITALY("ITALY", true, 106),
    JAMAICA("JAMAICA", false, 108),
    JAPAN("JAPAN", false, 109),
    JORDAN("JORDAN", false, 111),
    KAZAKHSTAN("KAZAKHSTAN", false, 112),
    KENYA("KENYA", false, 113),
    KIRIBATI("KIRIBATI", false, 114),
    KOREA("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", false, 115),
    KUWAIT("KUWAIT", false, 118),
    KYRGYZSTAN("KYRGYZSTAN", false, 119),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("LAO PEOPLE'S DEMOCRATIC REPUBLIC", false, 120),
    LATVIA("LATVIA", true, 121),
    LEBANON("LEBANON", false, 122),
    LESOTHO("LESOTHO", false, 123),
    LIBERIA("LIBERIA", false, 124),
    LIBYAN_ARAB_JAMAHIRIYA("LIBYAN ARAB JAMAHIRIYA", false, 125),
    LIECHTENSTEIN("LIECHTENSTEIN", false, 126),
    LITHUANIA("LITHUANIA", true, 127),
    LUXEMBOURG("LUXEMBOURG", true, 128),
    MACAU("MACAU", false, 129),
    MACEDONIA("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", false, 130),
    MADAGASCAR("MADAGASCAR", false, 131),
    MALAWI("MALAWI", false, 133),
    MALAYSIA("MALAYSIA", false, 134),
    MALDIVES("MALDIVES", false, 135),
    MALI("MALI", false, 136),
    MALTA("MALTA", true, 137),
    MARSHALL_ISLANDS("MARSHALL ISLANDS", false, 138),
    MARTINIQUE("MARTINIQUE", false, 139),
    MAURITANIA("MAURITANIA", false, 140),
    MAURITIUS("MAURITIUS", false, 141),
    MAYOTTE("MAYOTTE", false, 142),
    MEXICO("MEXICO", false, 144),
    MICRONESIA("MICRONESIA, FEDERATED STATES OF", false, 145),
    MOLDOVA("MOLDOVA, REPUBLIC OF", false, 146),
    MONACO("MONACO", false, 147),
    MONGOLIA("MONGOLIA", false, 148),
    MONTSERRAT("MONTSERRAT", false, 150),
    MOROCCO("MOROCCO", false, 151),
    MOZAMBIQUE("MOZAMBIQUE", false, 152),
    MYANMAR("MYANMAR", false, 153),
    NAMIBIA("NAMIBIA", false, 154),
    NAURU("NAURU", false, 155),
    NEPAL("NEPAL", false, 156),
    NETHERLANDS("NETHERLANDS", true, 157),
    NETHERLANDS_ANTILLES("NETHERLANDS ANTILLES", false, 158),
    NEW_CALEDONIA("NEW CALEDONIA", false, 160),
    NEW_ZEALAND("NEW ZEALAND", false, 161),
    NICARAGUA("NICARAGUA", false, 162),
    NIGER("NIGER", false, 163),
    NIGERIA("NIGERIA", false, 164),
    NIUE("NIUE", false, 165),
    NORTHERN_MARIANA_ISLANDS("NORTHERN MARIANA ISLANDS", false, 194),
    NORWAY("NORWAY", false, 166),
    OMAN("OMAN", false, 167),
    PAKISTAN("PAKISTAN", false, 168),
    PALAU("PALAU", false, 169),
    PALESTINIAN("PALESTINIAN TERRITORY, Occupied", false, 170),
    PANAMA("PANAMA", false, 171),
    PAPUA_NEW_GUINEA("PAPUA NEW GUINEA", false, 172),
    PARAGUAY("PARAGUAY", false, 173),
    PERU("PERU", false, 174),
    PHILIPPINES("PHILIPPINES", false, 175),
    POLAND("POLAND", true, 176),
    PORTUGAL("PORTUGAL", true, 177),
    PUERTO_RICO("PUERTO RICO", false, 178),
    QATAR("QATAR", false, 179),
    REUNION("REUNION", false, 180),
    ROMANIA("ROMANIA", true, 181),
    RUSSIAN_FEDERATION("RUSSIAN FEDERATION", false, 183),
    RWANDA("RWANDA", false, 184),
    SAINT_KITTS_AND_NEVIS("SAINT KITTS AND NEVIS", false, 188),
    SAINT_LUCIA("SAINT LUCIA", false, 189),
    SAINT_PIERRE_AND_MIQUELON("SAINT PIERRE AND MIQUELON", false, 192),
    SAINT_VINCENT_AND_THE_GRENADINES("SAINT VINCENT AND THE GRENADINES", false, 193),
    SAN_MARINO("SAN MARINO", false, 197),
    SAO_TOME_AND_PRINCIPE("SAO TOME AND PRINCIPE", false, 198),
    SAUDI_ARABIA("SAUDI ARABIA", false, 199),
    SENEGAL("SENEGAL", false, 201),
    SERBIA_AND_MONTENEGRO("SERBIA AND MONTENEGRO", false, 202),
    SEYCHELLES("SEYCHELLES", false, 203),
    SIERRA_LEONE("SIERRA LEONE", false, 204),
    SINGAPORE("SINGAPORE", false, 205),
    SLOVAKIA("SLOVAKIA", true, 206),
    SLOVENIA("SLOVENIA", true, 207),
    SOLOMON_ISLANDS("SOLOMON ISLANDS", false, 208),
    SOMALIA("SOMALIA", false, 209),
    SOUTH_AFRICA("SOUTH AFRICA", false, 210),
    SPAIN("SPAIN", true, 212),
    SRI_LANKA("SRI LANKA", false, 213),
    SUDAN("SUDAN", false, 214),
    SURINAME("SURINAME", false, 215),
    SWAZILAND("SWAZILAND", false, 216),
    SWEDEN("SWEDEN", true, 217),
    SWITZERLAND("SWITZERLAND", false, 218),
    SYRIAN_ARAB_REPUBLIC("SYRIAN ARAB REPUBLIC", false, 219),
    TAIWAN("TAIWAN", false, 221),
    TAJIKISTAN("TAJIKISTAN", false, 222),
    TANZANIA("TANZANIA, UNITED REPUBLIC OF", false, 223),
    THAILAND("THAILAND", false, 224),
    TOGO("TOGO", false, 227),
    TONGA("TONGA", false, 228),
    TRINIDAD_AND_TOBAGO("TRINIDAD AND TOBAGO", false, 229),
    TUNISIA("TUNISIA", false, 230),
    TURKEY("TURKEY", false, 231),
    TURKMENISTAN("TURKMENISTAN", false, 232),
    TURKS_AND_CAICOS_ISLANDS("TURKS AND CAICOS ISLANDS", false, 233),
    TUVALU("TUVALU", false, 234),
    UGANDA("UGANDA", false, 235),
    UKRAINE("UKRAINE", false, 236),
    UNITED_ARAB_EMIRATES("UNITED ARAB EMIRATES", false, 237),
    UNITED_KINGDOM("UNITED KINGDOM", true, 238),
    UNITED_STATES("UNITED STATES", false, 241),
    URUGUAY("URUGUAY", false, 240),
    UZBEKISTAN("UZBEKISTAN", false, 242),
    VANUATU("VANUATU", false, 243),
    VATICAN("VATICAN CITY STATE (HOLY SEE)", false, 244),
    VENEZUELA("VENEZUELA", false, 245),
    VIET_NAM("VIET NAM", false, 246),
    WALLIS_AND_FUTUNA_ISLANDS("WALLIS AND FUTUNA ISLANDS", false, 248),
    YEMEN("YEMEN", false, 252),
    ZAMBIA("ZAMBIA", false, 253),
    ZIMBABWE("ZIMBABWE", false, 254)
	;

	private String name;
	private boolean europeanUnion;
	private int id;
	private static Map<String, Countries> countryMap = new HashMap<String, Countries>();

	static {
	    for(Countries country : Countries.values()) {
	        countryMap.put(country.name(), country);
	    }
	}

	private Countries(String name, boolean europeanUnion, int id){
		this.name = name;
		this.europeanUnion = europeanUnion;
		this.id = id;
	}

	public static Countries ofValue(String countryName) {
	    return countryMap.get(countryName);
	}

	@Override
	public String toString() {
		return name;
	}

	public boolean isEuropeanUnionCountry(){
		return europeanUnion;
	}
	
	public Integer getId() {
	    return id;
	}

	public static void main(String[] args) {
        System.out.println(Countries.ofValue("ZAMBIA"));
        System.out.println(Countries.ofValue("AAA"));
    }
}
