package sk.seges.acris.site.shared.domain.mock;

import java.util.Date;
import java.util.List;

import sk.seges.acris.site.server.domain.api.ContentData;
import sk.seges.acris.site.server.domain.api.ContentPkData;


public class MockContent implements ContentData {

	private static final long serialVersionUID = 7293316505683824943L;

	private String niceUrl = "test";

	@Override
	public String getKeywords() {
		return "Offline content generator, Google Web Toolkit, Acris framework, Seges ltd";
	}

	@Override
	public void setKeywords(String keywords) {
	}

	@Override
	public String getDescription() {
		return "Offline content generated by Acris generator";
	}

	@Override
	public void setDescription(String description) {
	}

	@Override
	public String getTitle() {
		return getNiceUrl() + " - Page generated by Acris generator";
	}

	@Override
	public void setTitle(String title) {
	}

	@Override
	public String getNiceUrl() {
		return niceUrl;
	}

	@Override
	public void setNiceUrl(String niceUlr) {
		this.niceUrl = niceUlr;
	}

	@Override
	public String getWebId() {
		return "test";
	}

	@Override
	public void setWebId(String webId) {
	}

	@Override
	public String getPageName() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setPageName(String pageName) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getToken() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setToken(String token) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getLabel() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setLabel(String label) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Integer getIndex() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setIndex(Integer index) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getRef() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setRef(String ref) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getStylePrefix() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setStylePrefix(String stylePrefix) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Date getCreated() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setCreated(Date created) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Date getModified() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setModified(Date modified) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getPosition() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setPosition(String position) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getGroup() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setGroup(String group) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Boolean getDefaultlyLoaded() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDefaultlyLoaded(Boolean defaultlyLoaded) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getDefaultStyleClass() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDefaultStyleClass(String defaultStyleClass) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getMenuItems() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setMenuItems(String menuItems) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getDecoration() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDecoration(String decoration) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Boolean getHasChildren() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setHasChildren(Boolean hasChildren) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Integer getVersion() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setVersion(Integer version) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getParams() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setParams(String params) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setId(ContentPkData t) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ContentPkData getId() {
		return new ContentPkData() {
			
			private static final long serialVersionUID = 6394762952316919938L;

			@Override
			public void setLanguage(String language) {
			}
			
			@Override
			public String getLanguage() {
				return "sk";
			}
			
			@Override
			public void setWebId(String webId) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public String getWebId() {
				return "test";
			}
			
			@Override
			public Long getId() {
				return 0L;
			}
			
			@Override
			public void setId(Long t) {
			}
		};
	}
	
	@Override
	public Long getIdForACL() {
		return Long.valueOf(getId().toString().hashCode());
	}

	@Override
	public Class<?> getSecuredClass() {
		return getClass();
	}

	@Override
	public List<? extends ContentData> getSubContents() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setSubContents(List<? extends ContentData> subContents) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ContentData getParent() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setParent(ContentData parent) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getServerParams() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setServerParams(String serverParams) {
		// TODO Auto-generated method stub
		
	}
}