package sk.seges.acris.generator.server.processor;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

import sk.seges.acris.generator.rpc.domain.GeneratorToken;

@Service
public class ContentInfoProvider {
	public String getContentKeywords(GeneratorToken token) {
		return "Offline content generator, Google Web Toolkit, Acris framework, Seges ltd";
	}

	public String getContentDescription(GeneratorToken token) {
		return "Offline content generated by Acris generator";
	}

	public String getContentTitle(GeneratorToken token) {
		return token.getNiceUrl() + " - Page generated by Acris generator";
	}
	
	public boolean exists(GeneratorToken token) {
		return true;
	}
	
	public List<String> getAvailableNiceurls(String lang, String webId) {
		return new ArrayList<String>();
	}
}