package sk.seges.acris.site.shared.domain.mock;

import sk.seges.acris.domain.shared.domain.api.ContentData;


public class MockContent implements ContentData<Long> {

	private static final long serialVersionUID = 7293316505683824943L;

	@Override
	public void setId(Long t) {
	}

	@Override
	public Long getId() {
		return 0L;
	}

	@Override
	public String getKeywords() {
		return "Offline content generator, Google Web Toolkit, Acris framework, Seges ltd";
	}

	@Override
	public void setKeywords(String keywords) {
	}

	@Override
	public String getDescription() {
		return "Offline content generated by Acris generator";
	}

	@Override
	public void setDescription(String description) {
	}

	@Override
	public String getTitle() {
		return getNiceUrl() + " - Page generated by Acris generator";
	}

	@Override
	public void setTitle(String title) {
	}

	@Override
	public String getNiceUrl() {
		return "test";
	}

	@Override
	public void setNiceUrl(String niceUlr) {
	}

	@Override
	public String getContentDetached() {
		return "Test";
	}

	@Override
	public void setContentDetached(String content) {
	}

	@Override
	public boolean isDefaultContent() {
		return true;
	}

	@Override
	public void setDefaultContent(boolean isDefaultContent) {
	}

	@Override
	public String getWebId() {
		return "test";
	}

	@Override
	public void setWebId(String webId) {
	}
}