package sk.seges.acris.generator.server.processor;

import java.util.ArrayList;
import java.util.List;

import sk.seges.acris.generator.rpc.domain.GeneratorToken;

public class MockContentInfoProvider implements IContentInfoProvider {

	public String findNiceurlForLanguage(String originalNiceUrl, String targetLanguage, String webId) {
		return originalNiceUrl;
	}
	
	public String getContentKeywords(GeneratorToken token) {
		return "Offline content generator, Google Web Toolkit, Acris framework, Seges ltd";
	}

	public String getContentDescription(GeneratorToken token) {
		return "Offline content generated by Acris generator";
	}

	public String getContentTitle(GeneratorToken token) {
		return token.getNiceUrl() + " - Page generated by Acris generator";
	}
	
	public boolean exists(GeneratorToken token) {
		return true;
	}
	
	public List<String> getAvailableNiceurls(String lang, String webId) {
		return new ArrayList<String>();
	}

	@Override
	public boolean isDefaultContent(GeneratorToken token) {
		return false;
	}
}