package sk.seges.corpis.server.service.mock;

import sk.seges.corpis.core.server.annotation.service.AutoGenerated;
import sk.seges.corpis.core.server.annotation.service.Scaffolded;
import sk.seges.corpis.shared.model.mock.MockEntity;
import sk.seges.sesam.dao.ICrudDAO;

@Scaffolded
public class MockService extends MockServiceGenerated{
	
	public MockService(@AutoGenerated ICrudDAO<MockEntity> entityDao) {
		super(entityDao);
	}
	
	public MockEntity findByName(final String name) {
		return entityDao.findUnique(getPage().setFilterable(getCriteriaByName(name)));
	}
}